shared:
  seed: 123
  max_cache_size: 100_000
  samples_per_eval_length: 8
  num_eval_lengths : 8
  max_eval_length: 256

  # Scaffolding parameters
  min_motif_percent: 0.05 # 0.05
  max_motif_percent: 0.5 # 0.5
  motif_max_n_seg : 4

  inpainting_percent: 1 # all inpainting task
  crop_non_chain_residues: False
  non_chain_distance_threshold: 30


scope_dataset:
  seed: ${shared.seed}
  csv_path: ./metadata/scope_metadata.csv
  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 0
  inpainting_percent: ${shared.inpainting_percent}

  add_plddt_mask: False
  min_plddt_percent: 0.7
  max_eval_length: ${shared.max_eval_length}

  # Eval parameters
  samples_per_eval_length: ${shared.samples_per_eval_length}
  num_eval_lengths: ${shared.num_eval_lengths}

  # Filtering
  filter:
    max_num_res: 512 #128, 256?
    min_num_res: 60

  # Scaffolding
  min_motif_percent: ${shared.min_motif_percent}
  max_motif_percent: ${shared.max_motif_percent} 
  motif_max_n_seg : ${shared.motif_max_n_seg}

pdb_dataset:
  seed: ${shared.seed}
  csv_path: ./metadata/pdb_metadata.csv
  cluster_path: ./metadata/pdb.clusters
  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 512
  inpainting_percent: ${shared.inpainting_percent}

  add_plddt_mask: False
  min_plddt_threshold: 0.7
  max_eval_length: ${shared.max_eval_length}

  # Eval parameters
  samples_per_eval_length: ${shared.samples_per_eval_length}
  num_eval_lengths: ${shared.num_eval_lengths}

  # Filtering
  filter:
    max_num_res: 512
    min_num_res: 60
    max_coil_percent: 0.5
    rog_quantile: 0.96
    oligomeric: ['monomeric']
    num_chains: [1]

  # Scaffolding
  min_motif_percent: ${shared.min_motif_percent} 
  max_motif_percent: ${shared.max_motif_percent}
  motif_max_n_seg : ${shared.motif_max_n_seg}
  
AFDB_dataset:
  seed: ${shared.seed}
  csv_path: ./metadata/AFDB_metadata.csv
  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 256 # 256 for RAM
  inpainting_percent: ${shared.inpainting_percent}

  add_plddt_mask: True
  min_plddt_threshold: 0.8
  max_eval_length: ${shared.max_eval_length}

  # Eval parameters
  samples_per_eval_length: ${shared.samples_per_eval_length}
  num_eval_lengths: ${shared.num_eval_lengths}

  # Filtering
  filter:
    max_num_res: 256 #dataset max length is 256
    min_num_res: 60
    max_coil_percent: 0.5
    rog_quantile: 0.96

  # Scaffolding
  min_motif_percent: ${shared.min_motif_percent}
  max_motif_percent: ${shared.max_motif_percent} 
  motif_max_n_seg : ${shared.motif_max_n_seg}

cath_dataset:
  seed: ${shared.seed}
  csv_path: ./metadata/cath_metadata.csv
  domain_list_path: ./metadata/cath-domain-list.txt
  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 512 # 256 for RAM
  inpainting_percent: ${shared.inpainting_percent}

  add_plddt_mask: False
  min_plddt_threshold: 0.8
  max_eval_length: ${shared.max_eval_length}

  # Eval parameters
  samples_per_eval_length: ${shared.samples_per_eval_length}
  num_eval_lengths: ${shared.num_eval_lengths}

  # Filtering
  filter:
    max_num_res: 512 #dataset max length is 256
    min_num_res: 60
    max_coil_percent: 0.5
    rog_quantile: 0.96

  # Scaffolding
  min_motif_percent: ${shared.min_motif_percent}
  max_motif_percent: ${shared.max_motif_percent} 
  motif_max_n_seg : ${shared.motif_max_n_seg}


pdb_post2021_dataset:
  seed: ${shared.seed}
  csv_path: ./metadata/test_set_metadata.csv
  cluster_path: ./metadata/test_set_clusters.csv
  test_set_pdb_ids_path: ./metadata/test_set_pdb_ids.csv
  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 512
  inpainting_percent: ${shared.inpainting_percent}

  add_plddt_mask: False
  min_plddt_percent: 0.7
  max_eval_length: ${shared.max_eval_length}

  # Eval parameters
  samples_per_eval_length: ${shared.samples_per_eval_length}
  num_eval_lengths: ${shared.num_eval_lengths}

  # Filtering
  filter:
    max_num_res: 120
    min_num_res: 110
    max_coil_percent: 0.5
    rog_quantile: 0.96
    oligomeric: ['monomeric']
    num_chains: [1]
  
  # Scaffolding
  min_motif_percent: 0
  max_motif_percent: 0
  motif_max_n_seg : 1