pmpnn_dir: ./ProteinMPNN
folding:
  seq_per_sample: 8
  folding_model: esmf # esmf or af2
  own_device: False
  pmpnn_path: ./ProteinMPNN/
  pt_hub_dir: ./../.cache/torch/
  colabfold_path: path/to/colabfold-conda/bin/colabfold_batch # for AF2
  self_consistency_metric : scRMSD # scRMSD or scTM
  use_pae: true
  calculate_novelty: false